import 'package:flutter/cupertino.dart';
import 'package:lbz/assets/flaticon_icons.dart';

const String taxonomies = 'taxonomies';
const String popularAds = 'popular-ads';
const String ads = 'posts';
const String favorites = 'favorites';
Map<String, IconData> icon = {
  'alarm-bell': FlatIcon.alarm_bell,
  'bookmark': FlatIcon.bookmark,
  'favorite': FlatIcon.favorite,
  'like': FlatIcon.like,
  'home': FlatIcon.home,
  'message': FlatIcon.message,
  'user': FlatIcon.user,
  'building': FlatIcon.building,
  'office-building': FlatIcon.office_building,
  'team': FlatIcon.team,
  'house': FlatIcon.house,
  'responsive': FlatIcon.responsive,
  'advertisement': FlatIcon.advertisement,
  'magnifying-glass': FlatIcon.magnifying_glass,
  'down-arrow': FlatIcon.down_arrow,
  'electrical-appliances': FlatIcon.electrical_appliances,
  'furnitures': FlatIcon.furnitures,
  'plus-sign-in-a-black-circle': FlatIcon.plus_sign_in_a_black_circle,
  'sport-car': FlatIcon.sport_car,
  'right-arrow': FlatIcon.right_arrow,
  'left-arrow': FlatIcon.left_arrow,
  'phone-call': FlatIcon.phone_call,
  'email': FlatIcon.email,
  'pin': FlatIcon.pin,
  'bed': FlatIcon.bed,
  'plans': FlatIcon.plans,
  'tachometer': FlatIcon.tachometer,
  'car-insurance': FlatIcon.car_insurance,
  'star': FlatIcon.star,
  'warranty': FlatIcon.warranty,
  'color-palette': FlatIcon.color_palette,
  'calendar': FlatIcon.calendar,
  'sofa': FlatIcon.sofa,
  'user-1': FlatIcon.user_1,
  'clock': FlatIcon.clock,
  'apartment': FlatIcon.apartment,
  'date': FlatIcon.date,
  'cpu': FlatIcon.cpu,
  'ram': FlatIcon.ram,
  'cpu-tower': FlatIcon.cpu_tower,
  'share': FlatIcon.share,
  'comment': FlatIcon.comment,
  'filter': FlatIcon.filter,
  'sort': FlatIcon.sort,
  'check': FlatIcon.check,
  'send': FlatIcon.send,
  'ellipsis': FlatIcon.ellipsis,
  'arrow-point-to-right': FlatIcon.arrow_point_to_right,
  'arrow-down-sign-to-navigate': FlatIcon.arrow_down_sign_to_navigate,
  'arrowhead-thin-outline-to-the-left': FlatIcon.arrowhead_thin_outline_to_the_left,
  'navigate-up-arrow': FlatIcon.navigate_up_arrow,
  'image': FlatIcon.image,
  'attachment': FlatIcon.attachment,
  'close': FlatIcon.close,
  'edit': FlatIcon.edit,
  'delete': FlatIcon.delete,
  'bell': FlatIcon.bell,
  'bell-ring': FlatIcon.bell_ring,
  'customer-support': FlatIcon.customer_support,
  'save-instagram': FlatIcon.save_instagram,
  'log-out': FlatIcon.log_out,
  'language': FlatIcon.language,
  'account': FlatIcon.account,
  'key': FlatIcon.key,
  'bathtub': FlatIcon.bathtub,
};