/// Flutter icons Flaticon
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Flaticon
///      fonts:
///       - asset: fonts/Flaticon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class FlatIcon {



  FlatIcon._();
  static const _kFontFam = 'Flaticon';
  static const String? _kFontPkg = null;
  static const IconData alarm_bell = IconData(0xf101, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bookmark = IconData(0xf102, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData favorite = IconData(0xf103, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData like = IconData(0xf104, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xf105, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message = IconData(0xf106, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user = IconData(0xf107, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData building = IconData(0xf108, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData office_building = IconData(0xf109, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData team = IconData(0xf10a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData house = IconData(0xf10b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData responsive = IconData(0xf10c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData advertisement = IconData(0xf10d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData magnifying_glass = IconData(0xf10e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData down_arrow = IconData(0xf10f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData electrical_appliances = IconData(0xf110, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData furnitures = IconData(0xf111, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus_sign_in_a_black_circle = IconData(0xf112, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sport_car = IconData(0xf113, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData right_arrow = IconData(0xf114, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData left_arrow = IconData(0xf115, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phone_call = IconData(0xf116, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData email = IconData(0xf117, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pin = IconData(0xf118, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bed = IconData(0xf119, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bathtub = IconData(0xf11a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plans = IconData(0xf11b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tachometer = IconData(0xf11c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData car_insurance = IconData(0xf11d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star = IconData(0xf11e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData warranty = IconData(0xf11f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData color_palette = IconData(0xf120, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar = IconData(0xf121, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sofa = IconData(0xf122, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_1 = IconData(0xf123, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clock = IconData(0xf124, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData apartment = IconData(0xf125, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData date = IconData(0xf126, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cpu = IconData(0xf127, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ram = IconData(0xf128, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cpu_tower = IconData(0xf129, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share = IconData(0xf12a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comment = IconData(0xf12b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filter = IconData(0xf12c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sort = IconData(0xf12d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check = IconData(0xf12e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData send = IconData(0xf12f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ellipsis = IconData(0xf130, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_point_to_right = IconData(0xf131, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_down_sign_to_navigate = IconData(0xf132, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrowhead_thin_outline_to_the_left = IconData(0xf133, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData navigate_up_arrow = IconData(0xf134, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData image = IconData(0xf135, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData attachment = IconData(0xf136, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData close = IconData(0xf137, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit = IconData(0xf138, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData delete = IconData(0xf139, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bell = IconData(0xf13a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bell_ring = IconData(0xf13b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData customer_support = IconData(0xf13c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData save_instagram = IconData(0xf13d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData log_out = IconData(0xf13e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData language = IconData(0xf13f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData account = IconData(0xf140, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData key = IconData(0xf141, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wallet = IconData(0xf142, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData network_signal = IconData(0xf143, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData retweet = IconData(0xf144, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData refresh = IconData(0xf145, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check_1 = IconData(0xf146, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData read = IconData(0xf147, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData empty_folder = IconData(0xf148, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
